Restore compatibility with running on unmodified ioquake3
Remove additional acos and asin system call traps that I added in r119 (2012-09-15).
Now the implementations in bg_lib.c are used like when Q3Rally was a mod.
acos system call is part of Q3A CGame API. It's still used by Q3Rally CGame.

Attempting to run Q3Rally CGame VMs from Sep-2012 - Nov-2017 will now given an error.
ERROR: Bad cgame system trap: 112